### PR TITLE
Development

### PR DESCRIPTION
**Pull request by ojohnnyss**
Testing of tictactoe project. Classes Game, Player and GamePiece have tested.

### CODE REVIEW

**Review by JamesOkunlade — CHANGES_REQUESTED** [review]
### Test not working!!! 

You seem to have broken something in your code. There are some errors that prevented your tests from running. Please check and fix this. Your helper file seems to be missing.

There is commit just from one person, this is a collaborative project. I expect to see commit from the other person in your next review request.

Happy coding!

**Comment by ojohnnyss** [comment]
Hi, James!
All tests work, below screen for class Game (game_spec.rb). Tests for classes Player and GamePiece work too. Thing is Rspec "don't understand" what is chomp and my nested function input_player and after some my attempts I had to comments some functionality in code to pass tests.


I have a very good coding partner and I'm grateful him for his help and many pieces of advice during this course. But at the beginning course, I was an absolute beginner in ruby, because we decided to make tictactoe project solo and so our code was different last project was solo too.

**Comment by ojohnnyss** [comment]
File spec_helper.rb is located in dir spec (development branch)

**Comment by JamesOkunlade** [comment]
Hello,

You should request for another review so I can check it.

**Pull request merged**
